# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/nixed0_crypt";
    fsType = "btrfs";
    options = ["subvol=@"];
  };

  boot.initrd.luks.devices."nixed0_crypt".device = "/dev/disk/by-uuid/76ba56c3-b53d-4718-bdad-1780e66bd5c2";

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/ESP";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/nixed0_crypt";
    fsType = "btrfs";
    options = ["subvol=@nix"];
  };

  fileSystems."/.snapshots" = {
    device = "/dev/mapper/nixed0_crypt";
    fsType = "btrfs";
    options = ["subvol=@snapshots"];
  };

  fileSystems."/persist" = {
    device = "/dev/mapper/nixed0_crypt";
    fsType = "btrfs";
    options = ["subvol=@persist"];
  };

  fileSystems."/home" = {
    device = "/dev/mapper/nixed0_crypt";
    fsType = "btrfs";
    options = ["subvol=@home"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
