return {
  "nvim-treesitter/nvim-treesitter",
  dependencies = {
    'JoosepAlviste/nvim-ts-context-commentstring',
  },
  version = false,
  build = ":TSUpdate",
  event = { "BufReadPost", "BufNewFile" },
  cmd = { "TSUpdateSync" },
  config = function()
    require("nvim-treesitter.configs").setup({
      highlight = {
        enable = true,
        additional_vim_regex_highlighting = true,
        disable = { 'powershell' },
      },
      indent = {
        enable = true,
        disable = { 'yaml' },
      },
      ensure_installed = {
        "bash",
        "query",
        "c",
        "c_sharp",
        "cmake",
        "comment",
        "cpp",
        "css",
        "csv",
        "diff",
        "dockerfile",
        "elixir",
        "fsh",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "go",
        "gpg",
        "html",
        "http",
        "java",
        "javascript",
        "jsdoc",
        "json",
        "lua",
        "luadoc",
        "make",
        "markdown",
        "markdown_inline",
        "nix",
        "pascal",
        "passwd",
        "php",
        "phpdoc",
        "puppet",
        "python",
        "r",
        "regex",
        "ruby",
        "rust",
        "scala",
        "scss",
        "slint",
        "sql",
        "ssh_config",
        "svelte",
--      "swift",
        "terraform",
        "toml",
        "typescript",
        "vim",
        "vimdoc",
        "vue",
        "xml",
        "yaml",
      },
    })
  end,
}

