when:
  - event: pull_request
    branch: main

steps:
  - name: format
    image: nixos/nix:latest
    pull: true
    environment:
      NIX_CONFIG: "experimental-features = nix-command flakes"
    commands:
      - nix shell github:kamadorueda/alejandra --command alejandra .
  - name: push
    image: appleboy/drone-git-push
    settings:
      branch: ${CI_COMMIT_SOURCE_BRANCH}
      remote: ${CI_REPO_CLONE_SSH_URL}
      force: false
      commit: true
      commit_message: "style: auto-format code [ci skip]"
      ssh_key:
        from_secret: gh_key
      author_name: woodpecker-ci[bot]
      author_email: 20535246+uxodb@users.noreply.github.com
